# index #########################################################

smartcampus_accueil:
    path:  /
    defaults: { _controller: SmartCampusBundle:Smart:index }

# Visualisation #################################################

smartcampus_voirB:
    path:  /board/{id}
    defaults: { _controller: SmartCampusBundle:Smart:voirB }
    requirements :
        id: \d+
        
smartcampus_voir:
    path:  /capteur/{id}
    defaults: { _controller: SmartCampusBundle:Smart:voir }
    requirements :
        id: \d+

# Ajout ##########################################################

smartcampus_ajouterProp:
    path:  /ajouterProp/{id}
    defaults: { _controller: SmartCampusBundle:Smart:ajouterProp }
    requirements :
        id: \d+
        
smartcampus_ajouterB:
    path:  /ajouterB
    defaults: { _controller: SmartCampusBundle:Smart:ajouterB }
    
smartcampus_ajouterV:
    path:  /ajouterV
    defaults: { _controller: SmartCampusBundle:Smart:ajouterV }
    
smartcampus_ajouterP:
    path:  /ajouterP
    defaults: { _controller: SmartCampusBundle:Smart:ajouterP }

# Modification ##################################################

smartcampus_modifier:
    path:  /modifier/{id}
    defaults: { _controller: SmartCampusBundle:Smart:modifier }
    requirements:
        id: \d+

# Suppression ###################################################

smartcampus_supprimer:
    path:  /supprimer/{id}
    defaults: { _controller: SmartCampusBundle:Smart:supprimer }
    requirements:
        id: \d+
        
smartcampus_supprimerProp:
    path:  /supprimerProp/{id}
    defaults: { _controller: SmartCampusBundle:Smart:supprimerProp }
    requirements:
        id: \d+

# Json #########################################################

smartcampus_sensors:
    path:  /sensors
    defaults: { _controller: SmartCampusBundle:Smart:sensors }
    
smartcampus_sensor:
    path:  /sensors/{name}
    defaults: { _controller: SmartCampusBundle:Smart:sensor }
    