smartcampus_accueil:
    path:  /
    defaults: { _controller: SmartCampusBundle:Smart:index }

smartcampus_voirV:
    path:  /virtuel/{id}
    defaults: { _controller: SmartCampusBundle:Smart:voirV }
    requirements :
        id: \d+

smartcampus_voirP:
    path:  /physique/{id}
    defaults: { _controller: SmartCampusBundle:Smart:voirP }
    requirements :
        id: \d+

smartcampus_ajouterV:
    path:  /ajouterV
    defaults: { _controller: SmartCampusBundle:Smart:ajouterV }
    
smartcampus_ajouterP:
    path:  /ajouterP
    defaults: { _controller: SmartCampusBundle:Smart:ajouterP }

smartcampus_modifierV:
    path:  /modifierV/{id}
    defaults: { _controller: SmartCampusBundle:Smart:modifierV }
    requirements:
        id: \d+
        
smartcampus_modifierP:
    path:  /modifierP/{id}
    defaults: { _controller: SmartCampusBundle:Smart:modifierP }
    requirements:
        id: \d+

smartcampus_supprimer:
    path:  /supprimer/{id}
    defaults: { _controller: SmartCampusBundle:Smart:supprimer }
    requirements:
        id: \d+
        
smartcampus_redirect:
    path:  /redirect
    defaults: { _controller: SmartCampusBundle:Smart:redirect }