<?php

namespace Smart\CampusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EndpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndpointRepository extends EntityRepository
{
}
