<?php

namespace Smart\CampusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhysiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysiqueRepository extends EntityRepository
{
}
